# The configuration schema is defined by notes.proto file
# https://github.com/opendroid/gcp_go_funcs/blob/main/grpc_tests/notes/notes.proto
type: google.api.Service
config_version: 3

# Name of the 'notesgrpc' configuration. Note `*grpc` is required for it to deploy.
name: notesgrpc.endpoints.gcp-experiments-334602.cloud.goog

# API title to appear in the user interface (Google Cloud Console).
title: Notes gRPC Test API
apis:
  - name: notes.CreateNote
  - name: notes.GetNote
  - name: notes.GetNotesByAuthor
